### ISSUE TITLE
ResizeIt2 not positioning right edge of FF window past right edge of monitor

### ISSUE THREAD

**Issue by githwithit** [fuzzykiller/resizeit2#12]
[repeat of FF add on review, even with my issue it's the best FF resizer, thanks for your add on!]

ResizeIt2 is the best Firefox window resizing add on I have tried.
With Firefox ESR 102, ResizeIt2 worked perfectly, 5-stars! But...
With Firefox ESR 115, ResizeIt2 will not position the right edge of the Firefox window to the right edge of the monitor.
With ESR 102, I could use ResizeIt2 to position the right edge of the Firefox window 4pixels to the right edge of my monitor.
I want the right Firefox edge to the right of the monitor edge so I can quickly move my mouse to the right and page up/down and not grab the right edge of the Firefox window.
I can use Leomoon Hotkeyz to position Firefox windows like I want but it would be great if ResizeIt2 could do it instead.

**Comment by btzdnl** [comment]
Thanks for reporting this!

It sounds like you could be affected by [Firefox Bug 1811326](https://bugzilla.mozilla.org/show_bug.cgi?id=1811326) or the underlying code change. I will check that soon. If this is indeed the case, there is unfortunately nothing I can do; Firefox simply does not do what the extension tells it to do. This is unlikely to change even after the bug is fixed.

**Comment by btzdnl** [comment]
Looks like you are indeed affected by the underlying code change. It limits what extensions can do: Window size and position are constrained such that the window cannot be off-screen. Or at least, that’s the idea.

Using an external program to manage your Firefox window is your best bet. There is nothing I can do to make it work like it did before.

Sorry!

**Comment by githwithit** [comment]
Thanks for the detailed explanation, updated review to 5 stars!
