### ISSUE TITLE
add-on breaks clicking through to messages & notifications on Facebook

### ISSUE THREAD

**Issue by leggomyinfo** [fuzzykiller/resizeit2#7]
- facebook.com
- click messages icon or notifications icon
- click on a message or notification

<img width="615" alt="Screen Shot 2020-06-06 at 9 57 20 AM" src="https://user-images.githubusercontent.com/58055115/83945993-b268d280-a7fd-11ea-9421-bf974fbeebad.png">

**Comment by btzdnl** [comment]
I don’t see how this extension could influence Facebook. It does not interact with the browser in any way except:

* Setting keyboard shortcuts and getting notified about them
* Updating the currently active window’s size

I suggest you try again with a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) to verify the issue is actually related to the ResizeIT 2 extension. It could also simply be corrupted cache and/or cookies.

I don’t use Facebook, so you’ll have to investigate yourself.

**Comment by leggomyinfo** [comment]
Can't reproduce. I think it's another extension, or the interaction between the two.
